spring:
  application:
    name:
      gamified-habit-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

