spring:
  application:
    name:
      gamified-habit-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_mini_project
    username: 'nyfong'
    password: 'fongfong'


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
