spring:
  application:
    name:
      gamified-habit-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 30MB

minio:
  url: http://localhost:9000
  access:
    key: 0RiNo3lhiXsdAmb80wYD
    secret: 2KrS1OzBpF5TvoNtjknlVdgP6APGqsQJb5TJiucq
  bucket:
    name: btb-group1-mini-project-bucket



server:
  port: 9090

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
